import { db } from "./db";
import { agentDefinitions } from "@shared/schema";

const AGENT_DEFINITION_CATALOG = [
    // Engineering
    { name: "Frontend Developer", emoji: "🎨", division: "Engineering", specialty: "React/Vue/Angular, UI implementation, performance", description: "Builds pixel-perfect UIs and optimizes Core Web Vitals", whenToUse: "Modern web apps, pixel-perfect UIs, Core Web Vitals optimization", source: "agency-agents", color: "#3b82f6" },
    { name: "Backend Architect", emoji: "🏗️", division: "Engineering", specialty: "API design, database architecture, scalability", description: "Designs server-side systems, microservices, and cloud infrastructure", whenToUse: "Server-side systems, microservices, cloud infrastructure", source: "agency-agents", color: "#8b5cf6" },
    { name: "AI Engineer", emoji: "🤖", division: "Engineering", specialty: "ML models, deployment, AI integration", description: "Deploys ML models and builds AI-powered features", whenToUse: "Machine learning features, data pipelines, AI-powered apps", source: "agency-agents", color: "#06b6d4" },
    { name: "DevOps Automator", emoji: "🚀", division: "Engineering", specialty: "CI/CD, infrastructure automation, cloud ops", description: "Builds pipelines and manages deployment automation", whenToUse: "Pipeline development, deployment automation, monitoring", source: "agency-agents", color: "#10b981" },
    { name: "Security Engineer", emoji: "🔒", division: "Engineering", specialty: "Threat modeling, secure code review, security architecture", description: "Performs security audits and vulnerability assessments", whenToUse: "Application security, vulnerability assessment, security CI/CD", source: "agency-agents", color: "#ef4444" },
    { name: "Database Optimizer", emoji: "🗄️", division: "Engineering", specialty: "Schema design, query optimization, indexing strategies", description: "Tunes PostgreSQL/MySQL, debugs slow queries, plans migrations", whenToUse: "Query optimization, slow query debugging, migration planning", source: "agency-agents", color: "#f59e0b" },
    { name: "Software Architect", emoji: "🏛️", division: "Engineering", specialty: "System design, DDD, architectural patterns", description: "Makes architecture decisions and models domain systems", whenToUse: "Architecture decisions, domain modeling, system evolution strategy", source: "agency-agents", color: "#6366f1" },
    { name: "Code Reviewer", emoji: "👁️", division: "Engineering", specialty: "Constructive code review, security, maintainability", description: "Reviews PRs and maintains code quality standards", whenToUse: "PR reviews, code quality gates, mentoring through review", source: "agency-agents", color: "#84cc16" },
    { name: "Rapid Prototyper", emoji: "⚡", division: "Engineering", specialty: "Fast POC development, MVPs", description: "Builds quick proof-of-concepts and hackathon projects", whenToUse: "Quick proof-of-concepts, hackathon projects, fast iteration", source: "agency-agents", color: "#f97316" },
    // Design
    { name: "UI Designer", emoji: "🎯", division: "Design", specialty: "Visual design, component libraries, design systems", description: "Creates interface designs and ensures brand consistency", whenToUse: "Interface creation, brand consistency, component design", source: "agency-agents", color: "#ec4899" },
    { name: "UX Researcher", emoji: "🔍", division: "Design", specialty: "User testing, behavior analysis, research", description: "Conducts usability testing and extracts design insights", whenToUse: "Understanding users, usability testing, design insights", source: "agency-agents", color: "#a855f7" },
    { name: "Brand Guardian", emoji: "🎭", division: "Design", specialty: "Brand identity, consistency, positioning", description: "Develops and protects brand strategy and guidelines", whenToUse: "Brand strategy, identity development, guidelines", source: "agency-agents", color: "#14b8a6" },
    { name: "Whimsy Injector", emoji: "✨", division: "Design", specialty: "Personality, delight, playful interactions", description: "Adds joy, micro-interactions, Easter eggs, and brand personality", whenToUse: "Adding joy, micro-interactions, Easter eggs, brand personality", source: "agency-agents", color: "#f59e0b" },
    // Marketing
    { name: "Growth Hacker", emoji: "🚀", division: "Marketing", specialty: "Rapid user acquisition, viral loops, experiments", description: "Drives explosive growth through experiments and optimization", whenToUse: "Explosive growth, user acquisition, conversion optimization", source: "agency-agents", color: "#10b981" },
    { name: "Content Creator", emoji: "📝", division: "Marketing", specialty: "Multi-platform content, editorial calendars", description: "Builds content strategy and copywriting across channels", whenToUse: "Content strategy, copywriting, brand storytelling", source: "agency-agents", color: "#3b82f6" },
    { name: "SEO Specialist", emoji: "🔍", division: "Marketing", specialty: "Technical SEO, content strategy, link building", description: "Drives organic search growth and improves discoverability", whenToUse: "Driving sustainable organic search growth", source: "agency-agents", color: "#f59e0b" },
    { name: "LinkedIn Content Creator", emoji: "💼", division: "Marketing", specialty: "Personal branding, thought leadership, professional content", description: "Grows LinkedIn presence and builds B2B content", whenToUse: "LinkedIn growth, professional audience building, B2B content", source: "agency-agents", color: "#0077b5" },
    { name: "AI Citation Strategist", emoji: "🔮", division: "Marketing", specialty: "AEO/GEO, AI recommendation visibility, citation auditing", description: "Improves brand visibility across ChatGPT, Claude, Gemini, Perplexity", whenToUse: "Improving AI recommendation visibility and citation auditing", source: "agency-agents", color: "#8b5cf6" },
    // Sales
    { name: "Outbound Strategist", emoji: "🎯", division: "Sales", specialty: "Signal-based prospecting, multi-channel sequences, ICP targeting", description: "Builds pipeline through research-driven outreach", whenToUse: "Building pipeline through research-driven outreach, not volume", source: "agency-agents", color: "#f97316" },
    { name: "Deal Strategist", emoji: "♟️", division: "Sales", specialty: "MEDDPICC qualification, competitive positioning, win planning", description: "Scores deals, exposes pipeline risk, builds win strategies", whenToUse: "Scoring deals, exposing pipeline risk, building win strategies", source: "agency-agents", color: "#14b8a6" },
    { name: "Pipeline Analyst", emoji: "📊", division: "Sales", specialty: "Forecasting, pipeline health, deal velocity, RevOps", description: "Manages pipeline reviews and forecasting accuracy", whenToUse: "Pipeline reviews, forecast accuracy, revenue operations", source: "agency-agents", color: "#6366f1" },
    { name: "Account Strategist", emoji: "🗺️", division: "Sales", specialty: "Land-and-expand, QBRs, stakeholder mapping", description: "Drives post-sale expansion and NRR growth", whenToUse: "Post-sale expansion, account planning, NRR growth", source: "agency-agents", color: "#84cc16" },
    // Product
    { name: "Product Manager", emoji: "🧭", division: "Product", specialty: "Full lifecycle product ownership", description: "Handles discovery, PRDs, roadmap planning, GTM, and outcome measurement", whenToUse: "Discovery, PRDs, roadmap planning, GTM, outcome measurement", source: "agency-agents", color: "#ec4899" },
    { name: "Sprint Prioritizer", emoji: "🎯", division: "Product", specialty: "Agile planning, feature prioritization", description: "Manages sprint planning and resource allocation", whenToUse: "Sprint planning, resource allocation, backlog management", source: "agency-agents", color: "#3b82f6" },
    { name: "Feedback Synthesizer", emoji: "💬", division: "Product", specialty: "User feedback analysis, insights extraction", description: "Analyzes user feedback and extracts product priorities", whenToUse: "Feedback analysis, user insights, product priorities", source: "agency-agents", color: "#a855f7" },
    // Finance
    { name: "Financial Analyst", emoji: "📊", division: "Finance", specialty: "Financial modeling, forecasting, scenario analysis", description: "Builds three-statement models and supports data-driven decisions", whenToUse: "Three-statement models, variance analysis, data-driven business intelligence", source: "agency-agents", color: "#10b981" },
    { name: "Investment Researcher", emoji: "🔍", division: "Finance", specialty: "Due diligence, portfolio analysis, asset valuation", description: "Develops investment theses and performs market research", whenToUse: "Investment thesis development, risk assessment, market research", source: "agency-agents", color: "#f59e0b" },
    { name: "Tax Strategist", emoji: "🏛️", division: "Finance", specialty: "Tax optimization, multi-jurisdictional compliance", description: "Handles entity structuring, ETR analysis, and audit defense", whenToUse: "Entity structuring, ETR analysis, audit defense, strategic tax planning", source: "agency-agents", color: "#6366f1" },
    // Support
    { name: "Support Responder", emoji: "💬", division: "Support", specialty: "Customer service, issue resolution", description: "Handles customer support and user experience issues", whenToUse: "Customer support, user experience, support operations", source: "agency-agents", color: "#14b8a6" },
    { name: "Analytics Reporter", emoji: "📊", division: "Support", specialty: "Data analysis, dashboards, insights", description: "Builds business intelligence and tracks KPIs", whenToUse: "Business intelligence, KPI tracking, data visualization", source: "agency-agents", color: "#3b82f6" },
    { name: "Legal Compliance Checker", emoji: "⚖️", division: "Support", specialty: "Compliance, regulations, legal review", description: "Guides organizations through compliance certification", whenToUse: "Legal compliance, regulatory requirements, risk management", source: "agency-agents", color: "#ef4444" },
    // Specialized
    { name: "Agents Orchestrator", emoji: "🎭", division: "Specialized", specialty: "Multi-agent coordination, workflow management", description: "Coordinates complex projects requiring multiple agents", whenToUse: "Complex projects requiring multiple agent coordination", source: "agency-agents", color: "#f97316" },
    { name: "MCP Builder", emoji: "🔌", division: "Specialized", specialty: "Model Context Protocol servers, AI agent tooling", description: "Builds MCP servers that extend AI agent capabilities", whenToUse: "Building MCP servers that extend AI agent capabilities", source: "agency-agents", color: "#8b5cf6" },
    { name: "Automation Governance Architect", emoji: "⚙️", division: "Specialized", specialty: "Automation governance, n8n, workflow auditing", description: "Evaluates and governs business automations at scale", whenToUse: "Evaluating and governing business automations at scale", source: "agency-agents", color: "#10b981" },
    { name: "Recruitment Specialist", emoji: "🎯", division: "Specialized", specialty: "Talent acquisition, recruiting operations", description: "Handles recruitment strategy, sourcing, and hiring", whenToUse: "Recruitment strategy, sourcing, and hiring processes", source: "agency-agents", color: "#ec4899" },
    // ai-marketing-skills
    { name: "Growth Engine", emoji: "📈", division: "Marketing Ops", specialty: "Autonomous marketing experiments that run, measure, and optimize", description: "Runs autonomous growth experiments with pacing alerts and weekly scorecards", whenToUse: "Autonomous marketing experiments and growth optimization", source: "ai-marketing-skills", color: "#10b981" },
    { name: "Sales Pipeline Bot", emoji: "🔀", division: "Marketing Ops", specialty: "Turn anonymous website visitors into qualified pipeline", description: "Routes RB2B leads, resurrects dead deals, triggers prospecting sequences", whenToUse: "Anonymous visitor tracking, pipeline building, lead qualification", source: "ai-marketing-skills", color: "#3b82f6" },
    { name: "Content Ops Agent", emoji: "✍️", division: "Marketing Ops", specialty: "Ship content that scores 90+ every time", description: "Expert panel scoring, quality gate, editorial brain, quote mining", whenToUse: "Content quality assurance and editorial operations", source: "ai-marketing-skills", color: "#f59e0b" },
    { name: "Outbound Engine", emoji: "📬", division: "Marketing Ops", specialty: "ICP definition to emails in inbox — fully automated", description: "Cold outbound optimizer, lead pipeline, competitive monitor", whenToUse: "Fully automated outbound from ICP to inbox", source: "ai-marketing-skills", color: "#ef4444" },
    { name: "SEO Ops Agent", emoji: "🌐", division: "Marketing Ops", specialty: "Find the keywords your competitors missed", description: "Content attack briefs, GSC optimizer, trend scout", whenToUse: "Competitive keyword research and content gap analysis", source: "ai-marketing-skills", color: "#8b5cf6" },
    { name: "Finance Ops CFO", emoji: "💸", division: "Marketing Ops", specialty: "AI CFO that finds hidden costs in 30 minutes", description: "CFO briefing, cost estimator, scenario modeler", whenToUse: "Cost auditing and financial scenario modeling", source: "ai-marketing-skills", color: "#6366f1" },
    { name: "Revenue Intelligence", emoji: "💡", division: "Marketing Ops", specialty: "Prove content ROI and turn sales calls into strategy", description: "Gong insight pipeline, revenue attribution, client report generator", whenToUse: "Proving content ROI and extracting call intelligence", source: "ai-marketing-skills", color: "#14b8a6" },
    { name: "CRO Auditor", emoji: "🎯", division: "Marketing Ops", specialty: "Score any landing page, turn survey data into lead magnets", description: "Landing page scoring and survey-to-lead-magnet conversion", whenToUse: "Landing page optimization and lead magnet creation", source: "ai-marketing-skills", color: "#f97316" },
    { name: "Podcast Ops Agent", emoji: "🎙️", division: "Marketing Ops", specialty: "One episode → 20+ content pieces across every platform", description: "Transforms podcast episodes into full multi-platform content calendars", whenToUse: "Podcast content repurposing across platforms", source: "ai-marketing-skills", color: "#a855f7" },
    { name: "Autoresearch Agent", emoji: "🔬", division: "Marketing Ops", specialty: "Karpathy-inspired optimization loops for conversion content", description: "Generates 50+ variants, runs expert scoring, evolves winners", whenToUse: "Conversion content optimization with evolutionary loops", source: "ai-marketing-skills", color: "#84cc16" },
] as const;

/** Inserts the Agent Library catalog if the table is empty (required for hiring + CEO bootstrap). */
export function ensureAgentDefinitionsCatalog() {
  const existing = db.select().from(agentDefinitions).limit(1).all();
  if (existing.length > 0) return;
  console.log("[catalog] Installing agent definition library…");
  for (const def of AGENT_DEFINITION_CATALOG) {
    db.insert(agentDefinitions).values(def as any).run();
  }
}
